const { join } = require("path");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, "pages/**/*.{js,ts,jsx,tsx}"),
    join(__dirname, "components/**/*.{js,ts,jsx,tsx}"),
    join(__dirname, "app/**/*.{js,ts,jsx,tsx}"),
  ],
  theme: {
    colors: {
      core: {
        primary: "#755bff",
        inversePrimary: "#5b3ce8",
        onPrimary: "#000000",
        primaryContainer: "#4214d0",
        onPrimaryContainer: "#e5deff",
        secondary: "#c9c3dc",
        onSecondary: "#312e41",
        secondaryContainer: "#474459",
        onSecondaryContainer: "#e5dff9",
        tertiary: "#ecb8ce",
        onTertiary: "#482536",
        tertiaryContainer: "#613b4d",
        onTertiaryContainer: "#ffd8e7",
        fixed: {
          primaryFixedDim: "#5b3ce8",
          primaryFixed: "#755bff",
          primaryFixedBright: "#c8bfff",
          secondaryFixedDim: "#5f5c71",
          secondaryFixed: "#928ea5",
          secondaryFixedBright: "#c9c3dc",
          tertiaryFixedDim: "#7c5265",
          tertiaryFixed: "#b28397",
          tertiaryFixedBright: "#ecb8ce",
        },
      },
      extension: {
        fixed: {
          accentFixedDim: "#a000c0",
          accentFixed: "#dc52fa",
          accentFixedBright: "#f6adff",
          focusFixedDim: "#314edd",
          focusFixed: "#7287ff",
          focusedFixedBright: "#bac3ff",
          failureFixedDim: "#ba1a1a",
          failureFixed: "#ff5449",
          failureFixedBright: "#ffb4ab",
          successFixedDim: "#005233",
          successFixed: "#00a56c",
          successFixedBright: "#2ce198",
          brandFixedDim: "#bead16",
          brandFixed: "#feea56",
          brandFixedBright: "#fff08b",
        },
        accent: "#f6adff",
        onAccent: "#560068",
        accentContainer: "#7a0093",
        onAccentContainer: "#fed6ff",
        focus: "#bac3ff",
        onFocus: "#001f90",
        focusContainer: "#0830c5",
        onFocusContainer: "#dee0ff",
        failure: "#ff5449",
        onFailure: "#280001",
        failureContainer: "#93000a",
        onFailureContainer: "#ffdad6",
        success: "#2ce198",
        onSuccess: "#003822",
        successContainer: "#005233",
        onSuccessContainer: "#56feb2",
        brand: "#dbc836",
        onBrand: "#373100",
        brandContainer: "#504700",
        onBrandContainer: "#f8e451",
      },
      surface: {
        background: "#141414",
        inverseBackground: "#f9f9f9",
        inverseContainer: "#ececec",
        inverseContainerHighest: "#e2e2e2",
        backgroundDim: "#141414",
        backgroundBright: "#373737",
        containerLowest: "#070707",
        containerLow: "#1b1b1b",
        container: "#222222",
        containerHigh: "#292929",
        containerHighest: "#343434",
        fixed: {
          black: "#000000",
          white: "#ffffff",
          blackBright: "#222222",
          greyDimmest: "#303030",
          greyDim: "#3b3b3b",
          grey: "#474747",
          greyBright: "#c6c6c6",
        },
      },
      structure: {
        onSurface: "#fcfcfc",
        inverseOnSurface: "#0e0e0e",
        inverseScrim: "#ffffff",
        onSurfaceAlt: "#ababab",
        outline: "#928f99",
        outlineAlt: "#48454f",
        scrim: "#000000",
        shadow: "#000000",
      },
    },
    extend: {
      screens: {
        xs: "450px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        sourceCodePro: ["Source Code Pro", "monospace"],
        gronland: ["Gronland", "sans-serif"],
      },
      fontSize: {
        "header-xs": ["28px", { lineHeight: "32px", fontWeight: "500" }],
        "body-medium": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "caption-small": [
          "12px",
          {
            lineHeight: "16px",
            fontWeight: "400",
            fontFamily: "Source Code Pro",
          },
        ],
        "caption-medium": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "600",
            fontFamily: "Source Code Pro",
          },
        ],
        "header-4xs": ["16px", { lineHeight: "20px", fontWeight: "400" }],
        "header-2xs": ["23px", { lineHeight: "28px", fontWeight: "500" }],
        "body-small": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
